# Generated by Django 4.1.4 on 2022-12-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='id',
        ),
        migrations.AlterField(
            model_name='file',
            name='File_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
