# Generated by Django 4.1.6 on 2023-02-14 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_file_id_alter_file_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='Date',
            field=models.CharField(default='', max_length=300, verbose_name=datetime.date(2023, 2, 14)),
        ),
    ]
